---
app_name: simple-api
app_user: simpleapi
app_group: simpleapi
app_dir: /opt/simple-api
app_port: 5000

nginx_server_name: localhost

db_name: simple_api
db_user: simple_api_user
db_host: 127.0.0.1
