---
- name: Preconfigure Postfix mailer type
  ansible.builtin.debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: Local only
    vtype: select
  become: true

- name: Preconfigure Postfix mail name
  ansible.builtin.debconf:
    name: postfix
    question: postfix/mailname
    value: localhost
    vtype: string
  become: true

- name: Install Postfix
  ansible.builtin.apt:
    name: postfix
    state: present
  become: true

- name: Configure Postfix loopback interfaces
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^inet_interfaces ="
    line: "inet_interfaces = loopback-only"
  become: true
  notify: Restart postfix

- name: Ensure Postfix is enabled and started
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true
  become: true
