---

prerun: false
dependency:
  name: galaxy
  options:
    role-file: roles/requirements.yml
    requirements-file: collections/requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  export ANSIBLE_ROLES_PATH=${MOLECULE_EPHEMERAL_DIRECTORY}/roles
  export ANSIBLE_COLLECTIONS_PATH=${MOLECULE_EPHEMERAL_DIRECTORY}/collections
  ansible-lint --exclude ${MOLECULE_EPHEMERAL_DIRECTORY} -c .ansible-lint.yml
  flake8
platforms:
  - name: devops-dev-1
    box: onlyoffice/base-ubuntu2404
    memory: 2048
    cpus: 1
#    provider_options:
#      gui: true # Peut être nécessaire pour Windows (WSL)
    provider_override_args:
      - "vm.provision 'shell', inline: 'apt update'"
      - "vm.provision 'shell', inline: 'locale-gen fr_FR'"
      - "vm.provision 'shell', inline: 'locale-gen fr_FR.UTF-8'"
      - "vm.provision 'shell', inline: 'update-locale'"
    provision: true
provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg
    ANSIBLE_LIBRARY: "${VIRTUAL_ENV}/lib/python3.12/site-packages/molecule_vagrant/modules"
  inventory:
    links:
      hosts: ../../hosts/hosts_dev
      group_vars: ../../group_vars/
  playbooks:
    converge: ../../playbook_install.yml
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true
